html,
button,
input,
select,
textarea {
    color: #222;
}

body {
    font-size: 1em;
    line-height: 1.4;
    background-color: #000;
}

::-moz-selection {
    background: #b3d4fc;
    text-shadow: none;
}

::selection {
    background: #b3d4fc;
    text-shadow: none;
}

hr {
    display: block;
    height: 1px;
    border: 0;
    border-top: 1px solid #ccc;
    margin: 1em 0;
    padding: 0;
}


img {
    vertical-align: middle;
}

fieldset {
    border: 0;
    margin: 0;
    padding: 0;
}

textarea {
    resize: vertical;
}

.chromeframe {
    margin: 0.2em 0;
    background: #ccc;
    color: #000;
    padding: 0.2em 0;
}

@font-face {
    font-family: FuturaCondensed;
    src: url('FUTURAMC.ttf'),
    url('FUTURAMC.eot'); /* IE9+ */
}

/* Generated by Font Squirrel (http://www.fontsquirrel.com) on February 26, 2013 01:49:04 AM America/New_York */



@font-face {
    font-family: 'LaneNarrowRegular';
    src: url('LANENAR_-webfont.eot');
    src: url('LANENAR_-webfont.eot?#iefix') format('embedded-opentype'),
         url('LANENAR_-webfont.woff') format('woff'),
         url('LANENAR_-webfont.ttf') format('truetype'),
         url('LANENAR_-webfont.svg#LaneNarrowRegular') format('svg');
    font-weight: normal;
    font-style: normal;

}

@font-face {
    font-family: 'LaneUpperRegular';
    src: url('LANEUP__-webfont.eot');
    src: url('LANEUP__-webfont.eot?#iefix') format('embedded-opentype'),
         url('LANEUP__-webfont.woff') format('woff'),
         url('LANEUP__-webfont.ttf') format('truetype'),
         url('LANEUP__-webfont.svg#LaneUpperRegular') format('svg');
    font-weight: normal;
    font-style: normal;

}

@font-face {
    font-family: 'LanePoshRegular';
    src: url('LANEPOSH-webfont.eot');
    src: url('LANEPOSH-webfont.eot?#iefix') format('embedded-opentype'),
         url('LANEPOSH-webfont.woff') format('woff'),
         url('LANEPOSH-webfont.ttf') format('truetype'),
         url('LANEPOSH-webfont.svg#LanePoshRegular') format('svg');
    font-weight: normal;
    font-style: normal;

}


/* ===== Initializr Styles ==================================================
   Author: Jonathan Verrecchia - verekia.com/initializr/responsive-template
   ========================================================================== */

body {
    font: 16px/26px Verdana, Helvetica, Helvetica Neue, Arial;
    margin: 0;
    background-color: #000;
}



/* ==============
    MOBILE: Menu
   ============== */
.title {
    font-family: 'LaneNarrowRegular', sans-serif;
    font-size: 40px;
    text-align: center;
    color: #fff;
    padding: 7px 0 9px 47px;
    margin: 0;
    display: inline-block;
    background: url('/img/blip.gif') no-repeat 14px 13px;

}

.blip {
    width: 0.625em;
    height: 0.625em;
    background-color: #ff1430;
    position: relative;
    display: block;
    margin: 5px auto;
}

#navigation{
    position: absolute;
    overflow: hidden;
    top: 0;
    right: 0;
    display: inline-block;
}

nav.nav {
    display: inline-block;
    float: right;
}

nav.nav ul {
    list-style-type: none;
    padding: 0;
    margin: 0;
    float: right;
}

nav.nav li {
    text-align: center;
    float: left;
}

nav.nav a {
    display: inline-block;
    display: block;
    padding: 16px 25px 15px 25px;
    font-size: 18px;
    font-family: "LaneNarrowRegular";
    text-decoration: none;
    color: #fff;
    line-height: 1;
    margin-top: -50px;
}

nav.nav a:hover {
    color: #fff;
    text-decoration: none;
    background-color: #000;
    background-color: rgba(0,0,0,0.5);
    cursor: pointer;
}

.title, nav a {
    text-shadow: 0 1px 1px rgba(0,0,0,0.75);
}

 nav a:hover {
    text-shadow: none;
 }





.main-container {
    position: absolute;
    z-index: 2;
    width: 25%;
    right: -25%;
    top: 0;
    bottom: 48px;
    background: rgba(0,0,0,0.25);
}

.main {
    /*background: rgba(255,255,255,0.15);*/

}

article {
    color: #ccc;
    font-size: 12px;
    padding: 3em 6em;
}

article a {
    color: #fff;
}

#re {
    display: none;
}

.sidr {
    box-shadow: none;
}


#mobile-header {
    display: none;
    margin-top: 13px;
    position: relative;
    width: 20px;
    height: 20px;
    float: left;
    margin-left: 14px;
    margin-right: 13px;
}
















/* ==========================================================================
   Media Queries
   ========================================================================== */






@media only screen and (max-width: 785px) {
    #mobile-header {
        display: block;
    }

    #navigation {
        display: none;
    }

    .title {
        background: none;
        padding-left: 0;
    }

    #responsive-menu-button{
        background: url('../img/menu_blip.gif') no-repeat;
        width: 20px;
        height: 20px;
        text-indent: -9999em;
        display: block;
    }
}

@media only screen and (min-width: 786 px) {
    #responsive-menu-button{
        display: none;
    }
}





/* ==========================================================================
   Helper classes
   ========================================================================== */

.ir {
    background-color: transparent;
    border: 0;
    overflow: hidden;
    *text-indent: -9999px;
}

.ir:before {
    content: "";
    display: block;
    width: 0;
    height: 100%;
}

.hidden {
    display: none !important;
    visibility: hidden;
}

.visuallyhidden {
    border: 0;
    clip: rect(0 0 0 0);
    height: 1px;
    margin: -1px;
    overflow: hidden;
    padding: 0;
    position: absolute;
    width: 1px;
}

.visuallyhidden.focusable:active,
.visuallyhidden.focusable:focus {
    clip: auto;
    height: auto;
    margin: 0;
    overflow: visible;
    position: static;
    width: auto;
}

.invisible {
    visibility: hidden;
}

.clearfix:before,
.clearfix:after {
    content: " ";
    display: table;
}

.clearfix:after {
    clear: both;
}

.clearfix {
    *zoom: 1;
}

/* ==========================================================================
   Print styles
   ========================================================================== */

@media print {
    * {
        background: transparent !important;
        color: #000 !important; /* Black prints faster: h5bp.com/s */
        box-shadow:none !important;
        text-shadow: none !important;
    }

    a,
    a:visited {
        text-decoration: underline;
    }

    a[href]:after {
        content: " (" attr(href) ")";
    }

    abbr[title]:after {
        content: " (" attr(title) ")";
    }

    /*
     * Don't show links for images, or javascript/internal links
     */

    .ir a:after,
    a[href^="javascript:"]:after,
    a[href^="#"]:after {
        content: "";
    }

    pre,
    blockquote {
        border: 1px solid #999;
        page-break-inside: avoid;
    }

    thead {
        display: table-header-group; /* h5bp.com/t */
    }

    tr,
    img {
        page-break-inside: avoid;
    }

    img {
        max-width: 100%;
    }

    @page {
        margin: 0.5cm;
    }

    p,
    h2,
    h3 {
        orphans: 3;
        widows: 3;
    }

    h2,
    h3 {
        page-break-after: avoid;
    }
}



